---
title: "Manejo DataFrames 2"
output: github_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = TRUE)
```

## Working Directory

```{r}
setwd("~/AMV-21/Clase 2/DataFrame2")
```

## Llamado de Librerias

```{r message = FALSE, warning = FALSE}
library(UsingR)
library(DataExplorer)
```

## Leyendo los datos

```{r}
clima <- read.table("https://drvcruz.s3.us-east-2.amazonaws.com/SilwoodWeather.txt", header = T)
```

## Conociendo los datos

```{r Datos, message=FALSE}
names(clima)
attach(clima)
head(clima)
str(clima)
```

## Factor Analisis 

```{r boxplot mes, message=FALSE, warning=FALSE}
plot_boxplot(clima, by="month")
```


```{r}
plot_boxplot(clima, by="yr")
```


## plot

<https://www.datamentor.io/r-programming/plot-function/>
<https://r-coder.com/plot-r/#Plot_line_type>
<https://bookdown.org/yihui/rmarkdown/pdf-document.html>

```{r upper vs mes}
month<-factor(month)
plot(month,upper, xlab="Mes del Año", ylab="mm de lluvia")
text(7, 11, "Maximo")
```
```{r}

plot(clima$upper,clima$lower)
abline(lm(clima$upper~clima$lower), col="red")

```

```{r}
data(homeprice)
plot(homeprice$sale,homeprice$list)
abline(lm(homeprice$list~homeprice$sale), col="red")

```